version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: generate-app
          command: npm run generate
  deploy:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
      - run:
          name: install-sshpass
          command: 'sudo apt-get install sshpass'
      - run:
          name: remove-previous-deployed
          command: sshpass -p '$SSH_PASS' ssh $SSH_USER@$SSH_HOST rm -rf /home/xpaperchallenge/www/nlp/*
      - run:
          name: copy-app-to-remote
          command: sshpass -p '$SSH_PASS' scp -r ./dist/* $SSH_USER@$SSH_HOST:/home/xpaperchallenge/www/nlp
workflows:
  version: 2
  build-and-deploy: # deploy only from master branch
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
  nightly: # build and deploy at 12:00am
    jobs:
      - build
      - deploy:
          requires:
            - build
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master

